export const mockEmployees = [
    {
        id: 'EMP-A1B2C3D4',
        fullName: 'Rahul Sharma',
        gender: 'male',
        dob: '1990-05-15',
        state: 'Maharashtra',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-E5F6G7H8',
        fullName: 'Priya Patel',
        gender: 'female',
        dob: '1988-08-22',
        state: 'Gujarat',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-I9J0K1L2',
        fullName: 'Amit Kumar',
        gender: 'male',
        dob: '1995-02-10',
        state: 'Delhi',
        isActive: false,
        profileImage: null,
    },
    {
        id: 'EMP-M3N4O5P6',
        fullName: 'Sneha Reddy',
        gender: 'female',
        dob: '1992-11-30',
        state: 'Telangana',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-Q7R8S9T0',
        fullName: 'Vikram Singh',
        gender: 'male',
        dob: '1987-04-05',
        state: 'Punjab',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-U1V2W3X4',
        fullName: 'Anjali Gupta',
        gender: 'female',
        dob: '1993-09-18',
        state: 'Uttar Pradesh',
        isActive: false,
        profileImage: null,
    },
    {
        id: 'EMP-Y5Z6A7B8',
        fullName: 'Karthik Menon',
        gender: 'male',
        dob: '1991-01-25',
        state: 'Kerala',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-C9D0E1F2',
        fullName: 'Meera Iyer',
        gender: 'female',
        dob: '1989-07-12',
        state: 'Tamil Nadu',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-G3H4I5J6',
        fullName: 'Arjun Desai',
        gender: 'male',
        dob: '1994-03-08',
        state: 'Karnataka',
        isActive: false,
        profileImage: null,
    },
    {
        id: 'EMP-K7L8M9N0',
        fullName: 'Divya Nair',
        gender: 'female',
        dob: '1996-12-20',
        state: 'Kerala',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-O1P2Q3R4',
        fullName: 'Rajesh Verma',
        gender: 'male',
        dob: '1985-06-14',
        state: 'Rajasthan',
        isActive: true,
        profileImage: null,
    },
    {
        id: 'EMP-S5T6U7V8',
        fullName: 'Pooja Joshi',
        gender: 'female',
        dob: '1997-10-03',
        state: 'Madhya Pradesh',
        isActive: true,
        profileImage: null,
    },
];
